Develop
arxoangel61/1-html pull request #1
Opened 2024-05-21 19:04 UTC by arxoangel61

Здравствуйте!

1) 1-blog:
ветка develop:
Добавил готовую верстку с макета. (картинки, стили)

2) 2-form
ветка develop:
Добавил верстку с макета + стили 

Во 2 случае не стал полностью все верстать. Вдруг будете ругаться.

2024-05-21 20:24 UTC, Levitinn requested changes

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +        <header class="header">
![image](https://github.com/arxoangel61/1-html/assets/44999446/092fb4e5-b835-4621-9d13-dd4027c689bf)
некорректные отступы. сверху и снизу должен быть паддинг. у тебя сверху марджин, а снизу ничего

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +                <div class="header__logo">
логотип должен быть вне nav

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +                <div class="header__list">
излишняя обертка header__list

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +                    <span><p>B</p></span><p class="header__logo--text">Мой блог</p>
логотип должен быть ссылкой на главную страницу (href='/')

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +                        <li class="header__item">Frontend</li>
элементы навигации - должны быть ссылками, внутри li

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +    <div class="container">
не хорошо делать один контейнер на всю страницу. у каждой секции должен быть свой. бывает, что по дизайну, некоторые секции должны выходить за границу общей ширины. с общим контейнером ты так не сможешь сделать)

2024-05-21 20:24 UTC, Levitinn commented on 1-blog/index.html
> +                <div class="frontend__title">
лишняя обертка frontend__title. можно просто h1 без дива родителя

2024-05-22 13:58 UTC, arxoangel61 commented on 1-blog/index.html
> +        <header class="header">
Подскажите. Если отступ снизу идет от класса frontend в main, это является ошибкой? Можно конечно сделать отступы сверху и снизу, просто в данном случае все отступы от элементов сделал от верха через margin-top

2024-05-22 13:59 UTC, arxoangel61 commented on 1-blog/index.html
> +        <header class="header">
![image](https://github.com/arxoangel61/1-html/assets/56268062/ae6c2e3a-57ad-46be-80ec-6ec14c8bd93d)
вот

2024-05-23 20:02 UTC, Levitinn commented on 1-blog/index.html
> +        <header class="header">
![image](https://github.com/arxoangel61/1-html/assets/44999446/e7c9c12d-7f0c-4137-b850-c3573843af18)
сверху ( оранжевый )  должен быть паддингом хедера. у хедера верхний и нижний паддинг должны быть. нижний даст тебе отступ от main

2024-05-23 20:04 UTC, Levitinn commented on 1-blog/index.html
> +                <div class="header__list">
теперь header__nav лишний. самого ul достаточно как обертки

2024-05-23 20:04 UTC, Levitinn commented on 1-blog/index.html
> +                    <span><p>B</p></span><p class="header__logo--text">Мой блог</p>
ссылку не так указал.
![image](https://github.com/arxoangel61/1-html/assets/44999446/717e6b09-ac70-4108-b8dc-3eb981a7c73d)
поставь href='/'

2024-05-28 20:10 UTC, Levitinn commented on 1-blog/index.html
> +        <header class="header">
> у хедера верхний и нижний паддинг должны быть. нижний даст тебе отступ от main

вот это не исправлено. нижний паддинг отстутствует, зато есть верхний отступ у frontend которого быть не должно

2024-05-28 20:11 UTC, Levitinn requested changes
один комментарий

2024-05-30 20:15 UTC, Levitinn commented on 1-blog/index.html
> +        <header class="header">
не исправлено. сейчас падинг у бади. 
![image](https://github.com/arxoangel61/1-html/assets/44999446/7365360c-fb5b-4c3f-94da-100010a99b8a)
а должен быть у хедера.

> . у хедера верхний и нижний паддинг должны быть.
а так же, у бади есть нижний паддинг, которого быть не должно, тот должен принадлежать футеру

2024-05-30 21:26 UTC, arxoangel61 commented on 1-blog/index.html
> +        <header class="header">
Ну всееее
в этот раз точно все сделал :) я похоже прошлый раз не так понял, не много запутался

2024-06-04 11:29 UTC, Levitinn approved these changes

2024-06-04 12:04 UTC, merged