4 final
arxoangel61/1-html pull request #4
Opened 2024-07-02 15:46 UTC by arxoangel61

Добрый день!

Сделал финальный проект. Есть спорные моменты, которые решил, но не идеально по своему мнению.

1) Секция financial , реализация линии, долго думал как решить это, в итоге нашел только вариант, как реализовал, если есть решение лучше буду рад использовать.

2) Секция marketing - размеры у не которых картинок большие по области и тяжело сделать реализацию, как с макетом. Можно конечно поиграть с наложением блоков друг на друга, но не стал делать, в случае если есть вариант реализации лучше, рад буду использовать. 

В остальном по старался полностью соблюдать макету. Так как вариант планшетной версии не известен, много не придумывал постарался сделать по простому :)

2024-07-03 21:32 UTC, Levitinn approved these changes, later dismissed

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +    <header class="header container">
контейнер должен быть внутри хедера. и отступы справа и слева должны задаваться его шириной

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +    <header class="header container">
во всех остальных секциях такая же проблема

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +                <div class="financial__partners">
что за дикий отступ снизу? так быть не должно

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +        <section class="promo">
почему сверху марджин, а снизу паддинг?

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +                    <img src="img/balance.png" alt="баланс на конец месяца">
нет дива обертки. не заданы макс размеры

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +                  <div class="marketing__content">
некорректный отсуп. выравнивай элементы через флекс

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +                    <img src="img/report.png" alt="отчеты">
здесь и далее нет обертки и макс размеров

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +          <div class="container">
отступы сверху и снизу должны быть у секции, а у контейнера марджины

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +              <div class="container">
у контейнера никаких отступов от элементов

2024-07-03 21:32 UTC, Levitinn commented on 3-finio/index.html
> +        <section class="support">
с этой секцией что то не так. посмотри на ширину контента. текст выезжает из него

2024-07-03 21:37 UTC, Levitinn requested changes
оставил комменты

2024-07-07 11:43 UTC, arxoangel61 commented on 3-finio/index.html
> +    <header class="header container">
Исправил

2024-07-07 11:56 UTC, arxoangel61 commented on 3-finio/index.html
> +                <div class="financial__partners">
Уточнить.

2024-07-07 11:59 UTC, arxoangel61 commented on 3-finio/index.html
> +        <section class="promo">
Исправил

2024-07-07 12:25 UTC, arxoangel61 commented on 3-finio/index.html
> +                    <img src="img/balance.png" alt="баланс на конец месяца">
исправил

2024-07-07 12:32 UTC, arxoangel61 commented on 3-finio/index.html
> +                  <div class="marketing__content">
Уточнить

2024-07-07 12:32 UTC, arxoangel61 commented on 3-finio/index.html
> +                    <img src="img/report.png" alt="отчеты">
исправил

2024-07-07 12:47 UTC, arxoangel61 commented on 3-finio/index.html
> +          <div class="container">
Исправил

2024-07-07 12:49 UTC, arxoangel61 commented on 3-finio/index.html
> +              <div class="container">
Исправил

2024-07-07 15:03 UTC, arxoangel61 commented on 3-finio/index.html
> +        <section class="support">
исправил

2024-07-07 18:14 UTC, arxoangel61 commented on 3-finio/index.html
> +                <div class="financial__partners">
исправил (уменьшил отступ). Так как у нас пропадает элемент Ноутбука. Полоска поднимается вверх и через падинг в financial__partners оттягиваем ее вниз
![image](https://github.com/arxoangel61/1-html/assets/56268062/fba33bd3-b5c8-4d6e-a6e9-8854235bbe4b)
![image](https://github.com/arxoangel61/1-html/assets/56268062/cd10b53e-0699-499d-805d-a0bd52188167)

2024-07-08 09:45 UTC, arxoangel61 commented on 3-finio/index.html
> +                  <div class="marketing__content">
исправил

2024-07-10 08:59 UTC, Levitinn commented on 3-finio/index.html
> +    <header class="header container">
не годится. мы в прошлом задании, с тобой, кажется, уже обсуждали. нельзя задавать ширину страницы ограничивая body. Для этого есть контейнер, у которого всегда 
```
max-width: сколько-тоПХ;
width: 100%;
margin: 0 auto;
```

2024-07-10 09:00 UTC, Levitinn commented on 3-finio/index.html
> +    <header class="header container">
![image](https://github.com/arxoangel61/1-html/assets/44999446/56760ebc-7540-4631-ac49-b309957cb4a5) эти отступы лишние. сверху и снизу - это паддинг хедера. справа и слева - тебе даст контейнер

2024-07-10 09:06 UTC, Levitinn commented on 3-finio/index.html
> +                  <div class="marketing__content">
![image](https://github.com/arxoangel61/1-html/assets/44999446/62d1cfdd-00e2-427a-8146-29c76f70bf80)
некорректное свойство стиля

2024-07-11 19:35 UTC, arxoangel61 commented on 3-finio/index.html
> +                  <div class="marketing__content">
исправил

2024-07-11 19:36 UTC, arxoangel61 commented on 3-finio/index.html
> +    <header class="header container">
вроде все исправил

2024-07-13 19:42 UTC, Levitinn approved these changes

2024-07-13 20:29 UTC, merged